### ISSUE TITLE
Wrong dtype of return in date2num

### ISSUE THREAD

**Issue by zklaus** [ocefpaf/cf_units#202]
## 📚 Documentation

The documentation for [`cf_units.Unit.date2num`](https://github.com/SciTools/cf-units/blob/a69d7c81cc8a0da4dada191a0861020bd56f33f0/cf_units/__init__.py#L1944) and [`cf_units.date2num`](https://github.com/SciTools/cf-units/blob/a69d7c81cc8a0da4dada191a0861020bd56f33f0/cf_units/__init__.py#L352) stipulates that both functions return a `float, or numpy.ndarray of floats`. However, since the return value comes directly from `cftime.date2num`, this will regularly return "an array of integers" since cftime version 1.4.0 (see [the changelog](https://github.com/Unidata/cftime/blob/b3e5c740106051e7dcff500ee6de979091f5a37c/Changelog#L47)).

**Comment by pp-mo** [comment]
## Re-opened
I just realised that in addition to [`Unit.date2num(dates)`](https://github.com/SciTools/cf-units/blob/0ba82319a94b3d6b73ae8512507e04709869b4f9/cf_units/__init__.py#L1852), we **_also_** have a [`cf_units.date2num(dates, unit, calendar)`](https://github.com/SciTools/cf-units/blob/0ba82319a94b3d6b73ae8512507e04709869b4f9/cf_units/__init__.py#L329),
which is basically a different package for the same behaviours.

So unfortunately I think **_that_** docstring needs updating too.

**and...** we really need a whatsnew entry for these changes, too.
Sorry @ukmo-ccbunney I was so enthusiastic about #467 that I seem to have failed to review carefully !

**Comment by ukmo-ccbunney** [comment]
Fixed by #483
