### ISSUE TITLE
Unable to install cf_units on Mac OS for Python 3.9

### ISSUE THREAD

**Issue by alexgleith** [ocefpaf/cf_units#258]
## How to Reproduce
Steps to reproduce the behaviour:

1. Run `pip3 install cf-units` and receive an error:

>           patterns = self._get_platform_patterns(
>         File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/build_py.py", line 224, in _get_platform_patterns
>           spec.get('', []),
>       AttributeError: 'NoneType' object has no attribute 'get'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> note: This error originates from a subprocess, and is likely not a problem with pip.

2. Checkout the `main` branch from github, export relevant environment variables:

  * `UDUNITS2_INCDIR=/usr/local/Cellar/udunits/2.2.28/include/`
  * `export UDUNITS2_XML_PATH=/usr/local/Cellar/udunits/2.2.28/share/udunits/udunits2-common.xml`
 
get error:

>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/Cellar/udunits/2.2.28/include/ -I/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -c cf_units/_udunits2.c -o build/temp.macosx-12-x86_64-cpython-39/cf_units/_udunits2.o
>       In file included from cf_units/_udunits2.c:726:
>       In file included from /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4:
>       In file included from /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
>       In file included from /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:
>       /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
>       #warning "Using deprecated NumPy API, disable it with " \
>        ^
>       1 warning generated.
>       clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk build/temp.macosx-12-x86_64-cpython-39/cf_units/_udunits2.o -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib -Wl,-rpath,/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib -ludunits2 -o build/lib.macosx-12-x86_64-cpython-39/cf_units/_udunits2.cpython-39-darwin.so
>       ld: library not found for -ludunits2
>       clang: error: linker command failed with exit code 1 (use -v to see invocation)
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for cf-units
> Failed to build cf-units
> ERROR: Could not build wheels for cf-units, which is required to install pyproject.toml-based projects

## Expected Behaviour
Can install the package on a machine with `udunits2` installed on it.

## Environment 
 - OS & Version: Mac OS 12.4
 - Python: Python 3.9.13
 - cf-units Version: tried `3.0.1`, `3.0.1.post` and the `main` branch as at 29 Jun 2022

**Comment by alexgleith** [comment]
Just tried following the instructions in the INSTALL file and used:

`pip3 install --global-option=build_ext --global-option="-I/usr/local/Cellar/udunits/2.2.28/include" --global-option="-L/usr/local/Cellar/udunits/2.2.28/lib" .`

This failed with:

>       building 'cf_units._udunits2' extension
>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/Cellar/udunits/2.2.28/include -I/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -c cf_units/_udunits2.c -o build/temp.macosx-12-x86_64-cpython-39/cf_units/_udunits2.o
>       In file included from cf_units/_udunits2.c:726:
>       In file included from /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4:
>       In file included from /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
>       In file included from /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:
>       /usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
>       #warning "Using deprecated NumPy API, disable it with " \
>        ^
>       1 warning generated.
>       clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk build/temp.macosx-12-x86_64-cpython-39/cf_units/_udunits2.o -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib -Wl,-rpath,/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib -ludunits2 -o build/lib.macosx-12-x86_64-cpython-39/cf_units/_udunits2.cpython-39-darwin.so
>       ld: library not found for -ludunits2
>       clang: error: linker command failed with exit code 1 (use -v to see invocation)
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for cf-units
> Failed to build cf-units
> ERROR: Could not build wheels for cf-units, which is required to install pyproject.toml-based projects

**Comment by alexgleith** [comment]
I guess I should mention that I installed udunits2 with `brew install udunits2` and it works fine on the command line.

Also:

```
ls -lah /usr/local/Cellar/udunits/2.2.28/
total 24
drwxr-xr-x  10 alex  admin   320B 29 Jun 14:43 .
drwxr-xr-x   3 alex  admin    96B 29 Jun 14:43 ..
drwxr-xr-x   3 alex  admin    96B 29 Dec  2020 .brew
-rw-r--r--   1 alex  admin   1.9K 29 Dec  2020 COPYRIGHT
-rw-r--r--   1 alex  admin   949B 29 Jun 14:43 INSTALL_RECEIPT.json
-rw-r--r--   1 alex  admin   528B 29 Dec  2020 README
drwxr-xr-x   3 alex  admin    96B 29 Dec  2020 bin
drwxr-xr-x   5 alex  admin   160B 29 Dec  2020 include
drwxr-xr-x   5 alex  admin   160B 29 Dec  2020 lib
drwxr-xr-x   5 alex  admin   160B 29 Dec  2020 share
```

**Comment by rcomer** [comment]
Hi @alexgleith, cf-units v3.1 is now available on pypi and conda-forge.  Can you try with that?

**Comment by alexgleith** [comment]
Ok, tried using pip.

First time failed with:

> Building wheels for collected packages: cf_units
>   Building wheel for cf_units (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Building wheel for cf_units (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [18 lines of output]
>       Traceback (most recent call last):
>         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
>           main()
>         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
>           return _build_backend().build_wheel(wheel_directory, config_settings,
>         File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
>           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
>         File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
>           self.run_setup()
>         File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
>           exec(compile(code, __file__, 'exec'), locals())
>         File "setup.py", line 152, in <module>
>           package_data=get_package_data(),
>         File "setup.py", line 75, in get_package_data
>           raise ValueError(emsg)
>       ValueError: Require to set UDUNITS2_XML_PATH for a cf-units wheel build.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for cf_units
> Failed to build cf_units
> ERROR: Could not build wheels for cf_units, which is required to install pyproject.toml-based projects

So I exported the file location:

`export UDUNITS2_XML_PATH=/usr/local/Cellar/udunits/2.2.28/share/udunits/udunits2-common.xml`

now it fails with:

>       building 'cf_units._udunits2' extension
>       creating build/temp.macosx-12-x86_64-cpython-39
>       creating build/temp.macosx-12-x86_64-cpython-39/cf_units
>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include -I/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -c cf_units/_udunits2.c -o build/temp.macosx-12-x86_64-cpython-39/cf_units/_udunits2.o
>       cf_units/_udunits2.c:721:10: fatal error: 'udunits2.h' file not found
>       #include "udunits2.h"
>                ^~~~~~~~~~~~
>       1 error generated.
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for cf_units
> Failed to build cf_units
> ERROR: Could not build wheels for cf_units, which is required to install pyproject.toml-based projects

**Comment by alexgleith** [comment]
Any ideas on how I can get this installing on a Mac?

**Comment by bjlittle** [comment]
@alexgleith Thanks for taking the time to raise this issue, much appreciated.

Firstly, huge apologies. It really shouldn't be this painful. So I'd like to understand what's happening here, so that we can fix this for you and other macos users.

I don't have direct access to a Mac myself, but I might be able to work around that. 

First of all, is your MacOS 10.9+ ? Is it `x86_64` or `arm64` ?

From looking at all the diagnostics that you've provided above, particularly for the latest `cf-units` v3.1.0, it _seems_ like when you're performing the `pip install cf-units` it's not installing any of the `manylinux` binary wheels available for `py38`, `py39` or `py310`.

So, I'm assuming that it's defaulting to building the `sdist` instead. If that's the case, then you will require to set the following environment variables, which for your setup I'm guessing should be:

- `export UDUNITS2_INCDIR=/usr/local/Cellar/udunits/2.2.28/include`,
- `export UDUNITS2_LIBDIR=/usr/local/Cellar/udunits/2.2.28/lib`, and
- `export UDUNITS2_XML_PATH=/usr/local/Cellar/udunits/2.2.28/share/udunits/udunits2-common.xml`

Could you give that a try and let me know how it goes?

Also, for your workflow, are you forced to only use `pip`? Using `conda` instead isn't an option? Because that would "just work" :wink: 

Regardless, when you `pip` install, ideally it should install a binary wheel, and life would be much, much easier.

So I'll attempt to extend our support for providing compatible wheels for macos as well. Just give me your mac details and I'll see if I can get that to work for you :+1:

**Comment by alexgleith** [comment]
Hey @bjlittle 

The mac is `x86_64`.

And actually, just now the install with the three exports worked! I did try setting all these when installing from the master branch git repo a few days ago and it still wasn't working... I don't know what changed, but yeah, it installed!

So, thankyou!

> Collecting cf_units
>   Using cached cf-units-3.1.0.tar.gz (189 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from cf_units) (1.21.2)
> Requirement already satisfied: antlr4-python3-runtime==4.7.2 in /usr/local/lib/python3.9/site-packages (from cf_units) (4.7.2)
> Requirement already satisfied: cftime>=1.2 in /usr/local/lib/python3.9/site-packages (from cf_units) (1.4.1)
> Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/site-packages (from cf_units) (2.11.3)
> Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.9/site-packages (from jinja2->cf_units) (1.1.1)
> Building wheels for collected packages: cf_units
>   Building wheel for cf_units (pyproject.toml) ... done
>   Created wheel for cf_units: filename=cf_units-3.1.0-cp39-cp39-macosx_12_0_x86_64.whl size=236880 sha256=577f6d2d50270d7faeb70abfebc6892c22e588de17d7ed693addc0568efda21a
>   Stored in directory: /Users/alex/Library/Caches/pip/wheels/94/a5/36/8126158407af24b92668ab17d6458b6a1db603ac91ab8fa600
> Successfully built cf_units
> Installing collected packages: cf_units
>   DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> Successfully installed cf_units-3.1.0

**Comment by bjlittle** [comment]
Hey @alexgleith!

Awesome sauce! Glad that it finally worked for you :partying_face: :rocket: :100: 

Sorry again for the hassle, but thanks for hanging in there :beers: 

Are you happy for me to close this issue? 

If so, then I'll open a new issue and cross-reference this one with the purpose of supporting `x86_64` macos binary wheels. Would you be happy for me to ping you if and when I manage to build macos wheels, and if you have time, perhaps you could test install them at your end? That would be super helpful... but clearly, no obligation whatsoever :+1:

**Comment by alexgleith** [comment]
Yep, happy to close it. And yes, if you add me as a reviewer I'd be glad to test!
