### ISSUE TITLE
RTD is failing to build

### ISSUE THREAD

**Issue by bjlittle** [ocefpaf/cf_units#267]
## 🐛 Bug Report

For quite a while now the `cf-units` documentation on `readthedocs` has been failing to build and publish successfully, see [here](https://readthedocs.org/projects/cf-units/builds/).

**Comment by bjlittle** [comment]
Probably related to #258. Hmmm dunno :thinking:

**Comment by trexfeathers** [comment]
I was so pleased when we fixed it last time. Turns out it was just a flash in the pan:

![image](https://user-images.githubusercontent.com/40734014/178229863-5638a7fb-24b4-4372-bb0c-e7297f78ef46.png)

**Comment by trexfeathers** [comment]
Failures started again when we merged #214.
