### ISSUE TITLE
Add support for x86_64 macos wheels

### ISSUE THREAD

**Issue by bjlittle** [ocefpaf/cf_units#268]
## ✨ Feature Request

There is community appetite for `cf-units` wheels on MacOS `x86_64`, reference #258.

Contact @alexgleith.

**Comment by bjlittle** [comment]
Hey @alexgleith!

Fancy doing some testing?

So I've got a dev branch where I've successfully built MacOS `x86_64` wheels 🥳 ... can I take you up on the offer of testing?

Go to this [GitHub Action run](https://github.com/bjlittle/cf-units/actions/runs/2639364180) on my personal GitHub `bjlittle/cf-units` fork, and click the `pypi-artifacts` to download the built wheel assets `zip` file

![image](https://user-images.githubusercontent.com/2051656/178086154-173af71e-0731-4b67-b90d-ed8934aab7af.png)

Then `unzip pypi-artifacts.zip`, which should unpack 6 wheels and 1 sdist

![image](https://user-images.githubusercontent.com/2051656/178086299-32cc3224-8709-460c-89e1-4b998fc38efb.png)

3 of the wheels are for `linux`, and 3 of the wheels are for `macosx`, but all for `py38`, `py39` and `py310`.

Ignore the wheels version number for now (in my build environment it's defaulted to the bogus version of `2.0.3`), but choose one of the `macosx_10_9_x86_64` wheels to install... which I guess you're doing in a `conda` environment or a virtual environment.

e.g., simply `pip install cf_units-2.0.3.dev134-cp39-cp39-macosx_10_9_x86_64.whl`

I've built the `macosx` wheels in a [MacOS 11](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) container. If this isn't compatible with your OS, then I do have the option to build on [MacOS 12](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md).

Could you let me know if either of all of them work for you please?

Thanks so much 🙏 

P.S. I downloaded and installed the wheels on `linux` just fine

**Comment by alexgleith** [comment]
Looks fine to me!

`pip3 install /Users/alex/Downloads/pypi-artifacts/cf_units-2.0.3.dev134-cp39-cp39-macosx_10_9_x86_64.whl`

> DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
> Processing /Users/alex/Downloads/pypi-artifacts/cf_units-2.0.3.dev134-cp39-cp39-macosx_10_9_x86_64.whl
> Requirement already satisfied: cftime>=1.2 in /usr/local/lib/python3.9/site-packages (from cf-units==2.0.3.dev134) (1.4.1)
> Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/site-packages (from cf-units==2.0.3.dev134) (2.11.3)
> Requirement already satisfied: antlr4-python3-runtime==4.7.2 in /usr/local/lib/python3.9/site-packages (from cf-units==2.0.3.dev134) (4.7.2)
> Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from cf-units==2.0.3.dev134) (1.21.2)
> Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.9/site-packages (from jinja2->cf-units==2.0.3.dev134) (1.1.1)
> cf-units is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
> DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

**Comment by alexgleith** [comment]
``` Python
In [1]: import cf_units

In [2]: cf_units.__version__
Out[2]: '2.0.3.dev134'
```

**Comment by bjlittle** [comment]
Awesome, that's brilliant!

It just gives me the confidence that it actually works.

I'm going to make a pull-request and see if I can get another core dev to merge it. I'd then be keen for force a swift `cf-units` 3.1.0.post0 or 3.1.1 release to make them available to the community.

Thanks for all your help. Much appreciated indeed 🍻

**Comment by alexgleith** [comment]
It's great you're doing this work! Makes it all simple... including the udunits doesn't make the package bigger and will help people like me who just want to use the Python library!

**Comment by bjlittle** [comment]
No worries @alexgleith, glad to help!

Have fun playing, and don't hesitate to touch base with us again if you have any other questions or issues and we'll try our best to help.

Hopefully I can get my PR up and merged sometime next week, and get a release cut so that you can use the wheels straight from PyPI. So watch out for that.

Cheers :+1:
