### ISSUE TITLE
Release a macos 14 compatible release.

### ISSUE THREAD

**Issue by voney** [ocefpaf/cf_units#413]
## ✨ Feature Request
macOS 14.x compatible builds have been integrated into the CI chain, please release a new version (or re-release version 3.2.0 using the new CI)

## Motivation
cf-units via pip currently doesn't work on apple silicon/macos 14

## Additional context
I've tested out directly installing the library from main (with the correct udunits env vars) and it's working fine, at least from an installation point of view.

OS Version: `macOS 14.1.2 (23B92)`
Python Version: `Python 3.11.7`
pip version: `pip 23.3.1`
poetry version: `Poetry (version 1.7.1)`

**Comment by HGWright** [comment]
#458 has wheels building on macos 14, this is just waiting on a release and then it should be fixed.

**Comment by pp-mo** [comment]
Closed by #458
