### ISSUE TITLE
cf_units not working on macOS arm64

### ISSUE THREAD

**Issue by renaudjester** [ocefpaf/cf_units#438]
## 🐛 Bug Report

I did:
`pip install cfunits`
It was successful but then when I tried to import the package it failed.
I am on mac OS with apple chip M2 and python 3.11.6.

Here is the traceback of the error:
```
>>> import cf_units
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rjester/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/cf_units/__init__.py", line 23, in <module>
    from cf_units import _udunits2 as _ud
ImportError: dlopen(/Users/rjester/.asdf/installs/python/3.11.6/lib/python3.11/site-packages/cf_units/_udunits2.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_ut_ignore'
```
## How to Reproduce
Steps to reproduce the behaviour:

1. `pip install cfunits`
2. `python`
3. `>>> import cf_units`

## Expected Behaviour
I expect that cfunits can be imported without an error. 

## Environment 
 - MacOs Sonoma 14.6, apple chip M2
 - cf-units Version: cfunits-3.3.7

</details>

**Comment by ocefpaf** [comment]
Looks like support for it was added in https://github.com/SciTools/cf-units/pull/411 but there wasn't a new release or post release since then. @bjlittle Do you believe you can cut a post release to get py312 and osx-arm64 wheels on PyPI? It would be awesome if https://github.com/SciTools/cf-units/pull/423 and https://github.com/SciTools/cf-units/pull/427 could be merged too.

**Comment by trexfeathers** [comment]
Apologies, we're still struggling to make time for cf-units, but we have now allocated 2 weeks exclusively for this in September, so watch this space.

**Comment by HGWright** [comment]
This should be fixed by #458 which added building macos wheels on arm64 into the CI. Going to close this for now, and then after the next release this should be fixed for you, if its not please come back and let us know and we will reopen this.

**Comment by renaudjester** [comment]
Thanks a lot, I will let you know!

**Comment by lukasbindreiter** [comment]
I also just ran into this issue.
The last `cf-units` release was in April, so it seems people have been waiting for a while already - is there any planned in the near future?

**Comment by trexfeathers** [comment]
> I also just ran into this issue. The last `cf-units` release was in April, so it seems people have been waiting for a while already - is there any planned in the near future?

Yes, we're talking about it every day at the moment

**Comment by lukasbindreiter** [comment]
Awesome - thanks a lot, appreciate the effort  🙏 

And I don't know how much additional effort it would entail to add python 3.13 support as well - but since it was released just today timely support would be also very much appreciated for it too 😄

**Comment by pp-mo** [comment]
> @lukasbindreiter  add python 3.13 support as well 

Thanks for the prompt ! #506

FYI we aim to make a release within 1-2weeks now, 
mainly just to get the numpy 2 support + so align with [same in Iris](https://github.com/SciTools/iris/issues/6043), for the [Iris 3.11 release](https://github.com/SciTools/iris/discussions/5571).
