### ISSUE TITLE
update build system : adopt PEP517/8

### ISSUE THREAD

**Issue by pp-mo** [ocefpaf/cf_units#454]
AT LEAST replace setup.cfg

setup.py mat be required because of the Cython info

**Comment by bjlittle** [comment]
We still need a `setup.py` and we're already PEP517/8 compliant

**Comment by ocefpaf** [comment]
Indeed removing setup.py is good but not mandatory. In case of c-extensions, like this one, it is still easier to maintain. One alternative is mesonpy but I confess I did not like it and I'm using only for Fortran extensions b/c there is no better way at the moment.

TL;DR while the setup.py here could use a clean-up, it is still relevant and correct with modern packaging standards.

**Comment by bjlittle** [comment]
@ocefpaf Awesome, thanks :beers: 

I've also had a look at [meson](https://github.com/mesonbuild/meson), and it looks interesting, but I'm not sure whether using it as a build-backend would suit `cf-units` ... in particular, I fear that we've baked in some nasty dependencies on how `setuptools` works.

If we were serious about adopting `meson` we'd have to scope out the impact/effort involved vs the benefit.

There isn't something you know about that's going to break us when attempting to support `>py311` in `cf-units` whilst staying with `setuptools` ?

I noticed that [pyspharm](https://github.com/jswhit/pyspharm) opted to adopt `meson` for `py312` support ... but they're building upon Fortran, so I was guessing that was somehow related to the [numpy.disutils migration](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration). Any insight/advice on that?

**Comment by ocefpaf** [comment]
> I noticed that [pyspharm](https://github.com/jswhit/pyspharm) opted to adopt `meson` for `py312` support ... but they're building upon Fortran, so I was guessing that was somehow related to the [numpy.disutils migration](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration). Any insight/advice on that?

`setuptools` is still OK for most c-extensions on modern Python. I'm pretty sure we can drop the numpy.distutils, if that is still used here. I believe that the effort to move to meson is not worth it. I'd rather use that energy to ditch udunits2 and make it pure Python.

**Comment by bjlittle** [comment]
Cool 👍

Yup, dropping udunits2 would solve a lot of problems.

I'm 100% behind that 🎉
