### ISSUE TITLE
Fix docs build + enable on PRs

### ISSUE THREAD

**Issue by pp-mo** [ocefpaf/cf_units#486]
As for Iris, so we get checks on the docs build via RTD

Should also do a doctest check,

~We already seem to be getting that (cf #482)  "somehow", but I'm not sure how.~
(Update : pytest docs testing is configured [here](https://github.com/SciTools/cf-units/blob/d758886aa55b483b83f92316793ac90903d1ab9c/pyproject.toml#L38-L42) )

**Comment by pp-mo** [comment]
N.B. [pytest doctests --> Python standard-library doctest module](https://docs.pytest.org/en/7.1.x/how-to/doctest.html#how-to-run-doctests).
Sphinx interpretation is probably [the same](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#directive-doctest) , maybe not totally ?

**Comment by trexfeathers** [comment]
> N.B. [pytest doctests --> Python standard-library doctest module](https://docs.pytest.org/en/7.1.x/how-to/doctest.html#how-to-run-doctests). Sphinx interpretation is probably [the same](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#directive-doctest) , maybe not totally ?

https://github.com/SciTools/iris/issues/6110
